env:
  global:
    - secure: bd8rHzM702NUoUyxqSSeiFZswkeWmL1VGYMwo8cqMPC4DL1mXfxKrKbMXc/oN1pKWiwEnPdAZmiTUR1g0g4SqmkQWLS+T2xtiW0pnN06G1qzJiqO8nyUvaLyO3wT+0KFabIgviI4+YR76aIPxU8diLLOJOwakwcAzHPgq2Vp1qlQ73mNXWxP/9ufXAT5lljFlN0mLJRc1FvyjBD2WMd4mbWCMtcMstvKNA8nGSXVrAIobyugLtvugW152n4ftIHPMIaY3fFQh92sJBC8smJPMslZoK/FNGBTEmvTjIJ+hd4ymwZUf2pQqjmgbCPbGtfmb2SkljPaRtWiLpStkql0Prjc1l53BTi7cS0sbmBhDH+zr1taGft5dYAXDX0jDYRcI/71tgJFsQvx/tPKwEtWX5geFkb9OlnfcXTpXQnOgAiIkNSpYNqGrNyabHNi1tEJPCSnig3Qp+UQfjmDwgy7xebr5mCtpzGB6A+WsR5zhnW1DuV18Mc24rKTSH3dta5fzsq+KgqVpx82nbohcEBTzZZhGDMrdGiudWkZEu/Dlm5TeCWw3fXU4oE06gv7xbH4T361tTPp8o92UYCVo8SFZCYKoT4RQn7i1bZzMV/oeuBpn5BkYR17EYjIZcGhFXDNetMW3NouJfiUeCMeqwRlWhC+jxPv7JlMtG1uoY/rZyc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
