env:
  global:
    - secure: ssOG9X82x7TBvg1isc7F9XS8VgKGuCkiTDLzOaYbfjTZsrPDUv5ukv1wn10Np5Tt1prILGY07tMlbpCjFpSGQ1RDAkDX7OV4WMCh+a3xbA/ZvguVzQpFGHzdAw87lwWKg1XdsqDNMoaKnNoGBAY+HBqrw8Y2YKZKeMi6SWe0/HYl37aKfnMOIl7EL/yHYonJ3l2SAKYkCpvKc0hK3LGh0zwk20/rK3xDtXgpSLHQzjxHZbQ0bnOVHWmqsopBflC2/IE4MpqTGH3NUXxttIIlVmCRibKMil/XRz5sDS/LU+ZnWAcPCTyJYE3oKzMNk17mE2GuMkynJfus45c2zRy49tTJKcBdNNMIjJc/QwSl8uex8M8M61OjU0GYapyd0qNoLoGPOn06qiSz1iRqzdEBAtMnf0PtWuYpiGRQdKYfB+TksMJu0XAErESzSXW/Tv7V22eRCsUu7cclLA2Yqr47NtPBy785YU8ugIwtRE3Wdh44dO177G9YDYF/7Ci5/AzoMOilRNBRQGPeBLibF/cV4faU9cy69dJVy2fseyC+t54MzfS8YOOQnrwV/7Zxta+Jtf8zmwZcY2F/3B7ofk5wfDcyUXdDqSZmxqKgLXkXRS5SAAX5j2rBaHdMOJ7ACQ9ZYRryDmoXKaaZLyxmcrp0gdEFig7pfA4+F6MGCoBFT/Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
