env:
  global:
    - secure: IwCmL09ojO5AJNavUCc55Y9yxnt3FGfqyNEEaFA8AAd9OmuUb/NbWrjDKu9CtULvah0Rxe0gmQ8lTJX9DZWXw0qe/+AltEPaYM4vIlpRM6E1it0IxZ8KFBeknp04Oiva9aBlAO+Ul6UsN5W6pWKKSqZ6Cp4JZsR/20T6DeNWY5QcFEQq2qPujqLsWqNyAapIag/i/9x2Idn+P4eMfXfRMgAeL1vSZOtsY85pCiGEnBf1oEkg1knm4Mg5Zsg5XQG0hYVahOuK6ewIY9qYqT9IS7qFa9NCBuTcYW5BB77Gvm7zCrh6Ro17kXJ7MgT+5GndRH6PTXJ4IXsstluHk/WeZFAgnOFmNiC90r4HG+ip6ixZ4VP0WKXo3ctpg5I+4Z/1xQBHHZOMlSgJpHzRvZoT9L0lGka7yijwpozUkFlTuC2ktY7WxpETCG2nJwrxd+USi/29eyjeaXqsB9F2B6w3F3gIoVGgnGzXRZhmMrD1dQujZi38XlMY8FCkZoRVolajxE6iRu19dWVK7YPN6OCMQ+vjYlwmwVvWPJj71J+ypBbi0uo+esgRCHJ6okYh99YbWWUqvYl+ScOkYZofTBxSQH/lyyZUqJxc2OWIZSL6WURw00cZA8Do0Wvish235BTf1heHoIVHq57d2RaaOVAsLRaephmMmaevUxH5a1KNqNs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
