env:
  global:
    - secure: ghKytfnxG4bolSr4wQpeBYu5vJ2x6dlKOPj4wX1Ltof/X9X4zKK+YmAAgnlEODgyohUYWuUi/OKj8WZ8VuLsO5gJSu86IRb8TLzFRt8/8PzKbnJH/eRKhYkE/IWGx65IxyBZEdOyY0FY4PLLp2L6PAZHIhEkHA8mfiDKQC2z8hoDp4Qm8lBD/KDE9wMakZbI3UDDTCx/nQlWa5+PNkdiwZ6ZvcVC0/oFy4whN6ej9y5Usp8pMXT4ISJevyBf2Z8Rht0aFf/cvon+wAdUooxKMDPok4+K8z2E0cBD0xBxnByDKbuoJm6L2oMmu7HkXEPLtWXdThg+b/0XUGWruenUCZ0lMVoUTlEOBTNpKZqi3TNKb6IdIrbT7Mz1gD9tyUQ9DCV0Z+KCnisyMO76InEiJBBvgYu+uSRL0JMmSO1Oa8OD8h9JcnlD3T3xvFs8HAQ77kbNSCKz2NwH7VZZt/mHWpVAxwhfBj40fSBovCHhfwj9aW/Pf6czWBSZxd9QKP4x/LidPHy2lNv2itJMAoDmpjZgDB87JUbJDLiR2PMnR+GXWqRl57W+1uIXsZKWu0dEseRTnGfnhxnpky8UTbXbGswT1hsNByYZh4flSiqUQfzEGKx0qTvVA7iuQaEwayhutITngv8iDGTVVPaBtsdCsZsCKF+CToihBgGeiNhPbfc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
