env:
  global:
    - secure: HkHqX7a2LIa4+WsRwjL4r1GO96VLUteeFhCziMOgrpMvIHKHq377MuBh3ZPKfagu20Omgn55vV9klJx4mys+pII67LqqqOOZA7spV22UyCz4SbE0SqQ2NYIbqbMBeiI18LUhJHMWfdi0mRz3tGpqUPht6Z0sdwCkUj06wwoze9eFzJgxrrG4YEXBOGUPVJYY7iSh047scwJAeUpFVmlw5VHf1Z8EOCO9tfymTkDjiPtrNZ1+7d4lopMWR98cAQNJm3+QkHrvoWxWJsE4ss5v6EvNj0/q5oAemA+v5OcHWqk/oLdvaiHsiQ9AzvczEWLQmFh5oj3s4LH6OAtvKVem5N7HA0h+QyyZC17Zle7cj406M8T59HQr06zYux25Cbpebq3MzhOggYgJkgV2/nohhNqQvRGQsWib1jbVz69ecMnLZ6f0StRdvy8kTWmhSdXpsatRty4kS5iHZwBn8T2uGGB+A0+iciAXfYI8C/LHaivwk/YV6spXLwAUp+hRkLByUqQecd/M8HrHN5iag4IDUybGIE2SENjcxSObCzkwwSzWrJ9vhKgDWCcyASpyV1Bj2nRV5n4vQaByGJfY5T2XrlrABmttsNecrxzGz/ROFCAiio1XMd2+OxKm7Y6jeGL44Cd7MGlMjhlB1UZxRzMmHOmH6/5hhnu1D9sYKeLT7PM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
