env:
  global:
    - secure: KVEUzfhi58PYuWo9nSqf3Hc+aIVctujQ1zy48bzmw1X6ojaYFOB9zAPr4mbny6zOKQ17gkZzJL34DWZKz3TihrafN9z0TelsKcAHDMMiCepXjWQbQAnvQOOim30IlKWCj+j7M0M6mnHATl+yOw/u0IjYk+OlJ2BvcvsBF5ljBkfv2KTJSKHkt8Jghsad810E+Dk1haB828wWEUK5xG/5xb3xaSqBd5+6BIFeSZkTkzcUQOCps0KMdgtwFFDmDob8Rb1q8C0TfQxksjWTu8YAb3E1Xugq6FhmCZ3yGZxjmR+Wohg9q2Y5Oj8HWYCzkS9+U8YF2vsWMy3+IxYZr2UXsu9yRBNv07eTRwJEzjY2LFoj0NMtz0JssHMY+1g/QK8evIqfFMtRZksYYelE+3E5PsM4lQ7d5IvXRCQkzyXjXsXU3wxzYvwWQB1LQt6GBBmaNsIsAWWE5RVswm5PfV4drXuULJo7a5fJOyhxZ3nXap3KUiYo5L7mIeS0Evxg/zbSLPD217KVEUI7W/O2jl7FcAw5C8QNQO4LMXhdVbZg2l45AnJZB7vb4JW4otEdYlpjAxPKxFxDfKk5NuEMqUAw2Z1y1JAIGxL1E+5W4mNYFtOcW8W+66WF5YlY80YoeMtpASrU/J01xxOM6Pxhfko05m/vmaElU+8IjFI0E4WSkpc=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
