env:
  global:
    - secure: hfeyjLH3sVNtrLneeImrDCYBMYbhEAZ/FCW4H9gD6shy3XqxR1d/nqqqlrofyXaa1Niw7WDTTGlaxlrW5RLV4+EIkp9GE0XODulSjF1wxv9rx5lIH+MYWZeTiRLcpn3Qr8OR7ua6EtGlcmdUTo9qFCQtn2pcpI8P0cCbVrISVaRLaqv1ZmZXrYVCtER7aq/f3pYJm1mwVSMmuZAqlsBmrClBvxTY3qqKsTRz3I7FMbml07+xPKU7njn85ht4FHWCS0ITNlA26Pe6jZXuiQg2t64tNHuPNUZm2L8T9Bvbdef+WPrBVZC8eGMJWSC4hSorYQGDhTmcJcuiUjTcdVkekJZVoU3BcxqtwYnjkZC1vGyhFoJiWGyjZKuKz7qhDl+75rJPJZamru30CGqmnhSG+oqjeDMMTt8B7EC8hLileUVwWEVSt5qqymUTE26v0u1w+x0sw318D3yuf6umwuyjtY67R/mLXkWNOavAEGilqvpha8mlxjgEhVSNxkR41dAZcpcMnNnEJZ2GF1wHTMYkk3F+56vtnLHFwQZhxgwjPL9MKVPsVSRabzm8WKZLvSvD/WUa8hfohjuq0WS+CD7C6uxrPyBaliv3llTLBG0xh6ot/YAX5vI4hzzAXteZO1+Gg/i4ZYdAzSeJNDVxRhXxw6rhx5A15B2EwgCOLiGYo+Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
