env:
  global:
    - secure: ujJHlPyBM5hQZK6FPAiR9hOf2/zsGEj+uwe6Lkh5JdFq0Vzanr7NriSTzFONLFrQHwScgwb26C5+zTeJtrp3U2+C/Arxj1s8V3LkK94H9cF2TZdKAuCdvta5s4jes5JvmT8AlObcn9iIWbQNMtP32Xs1gulwA9eWB4GyYyDEfbAzJfENhPLv7f7bk5GUc0te2oLfjO213zqQeFfs6W+qGzOtcYDxjyK+jBsa6iZKmH/ztEFH2mksJSNVLCEjEXkSB8B3ibvaPXw9UlU9qkqiMepAljrGAJPtEvqAFAUzkp0EX0lKzPdwFWGz1Ifz2jgyDnHIgh79b2jRFJ/SfJNWCoo9GRaVHTQY0kofs2dL3w2Le8G3GH/r0+yXPwlGL/iM+6Za4zJgW2Sn9qhmUygtxGfHDQkRqCuZ6LAK3cYOxK3O3bl2ElJfyPEL5/M1zSoZRMAltafXzGWgZkv+Fg/N5QZOImk3X8BeQ1KDCX7gIGwzngEveJzifk+NHIIPlIkrOFbkTyYitgQLlx581eYlJph45jy5yP/2pSaYzUz9EhrX2RMqi+oqpijyAOjShdq7FWrqWP6b0IVYnE2F0kXNesb4x9jE35IN1NGHflB0uViwdZTQzc441jgze/0xh3aCnsOf2ukvX8qsddaQ71Di/XOEm9mxkuCmptuDtOGTpWo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
