env:
  global:
    - secure: cLRccfOIisrMooR8KZUTX76uyBULwc24RZ2NBNKGAsueLX91lORxNdLrydXjGwp7Q69uzt4ryDmmOsKi6Vic/0xX7V8WRIf4MkhIknZW3kebO3iGeWm/cNGJ9ds+oYkuWcKf0F+WTsXxt3EzxW5v3K3HDGuTUa/IkYkwSsfwT6/WFiptg+B+NVotWbruuvPeDi8c5t2ap4gVsXC6M76MJR1AynXPZkUaZlR86Wre4G2pbXLSrlabvzRUvH2PXO2zFvcWAbVBWCR+EaiB+LPGuDXbOm9WJ/T+24vJbRbc5eZ37vZIfQ4GEx8uqopPDbkIrniaUrRye9/6NJt2cEIjwt7psjrQ4kNCLxfM79EK1u5H6IvxQmiwX9GfWYBD5GnLNL/vKAQJgGwjN2/1vv5827+Swti+/OCpaMPI3JUS/Yd9HVwpZStcqg9LI0jPn/lP1JsH3xEKEh7wbUU1ouBBi8+h0py8Pifj17kTi0Ei/DDffU91VQ/6G/hmHoMLnLGbcU2C00zTIyzdK/38pIXGbtJ8s4RWgWjRe9GzWwU4XTVWb/kbi2gYZB46o3F/vbqgr5UgNTuFhxkXKrefDYOMg8/chXi2a/wYRmALfv1OfpppFyQVJBprcbo34YLz7XOABO2SB1veLgRTJeI6fSUJlWmKGI+3R017huDr0Cf8SVg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
