env:
  global:
    - secure: IUhKWGW/IvLhxWOaYwiwAMlSWvl8bpNpgxotgBjAcJKSOfNj2KJIYv8DThw1NhvJ95VgBq5I4XIh7PtoeAq8l78eg4oO8jOVQBXYeZzaQfZe9dUaOEPF7RpAB+MTxwhZg8dPSaylgQF2kkg12b+xfSwbzkGSPJNe3JN4Pe4NcyYsRjHFTDVAoWMNBw4RnGIKmRSdzZL8nNGixZzw2Z2hW6oFI7MKN5WbE/AzyUHB9t5v5Yc5UIJ3pN5SUr9GJxLTo12XuIJ5Q5sl9olButO6MiOcZQ17F4Ti5vvaZ15+Qu/M9++w68/6jTF6lq8Q++OI7ib0tZcx0304BhB9Pk0lpAehIu2Gy/YYndrqXlfiANc+gXTMyEHf/8fgZyO/QuLoGcGqPfG8Hh6E224dHb4yrmpRQJ9g0lt9yYnji83BnOBdZI1tNcJNjXo2m0r0+4FAnNGwRV5tD4vSbV02hn+MWq0ZYCuCNAkTf57y6hd8ufIoig6oRA5bGMWF/4w7ZgTmgEcjx45C7Aw5JXZgkCRvgi/BYOXacBF5aiAyNN1hG7qMP7wdXvjOALkzjGDmOUX5QVnR76GgZ/C76pfYKDqAv2CSppT0ZGDe5pFs8326HCeVSIcT27ARLkzSNe+xAvC8j9DdWYnB0ye8bg0Oo97vkvOEkxfLtiZnvePkKgPFfl8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
