env:
  global:
    - secure: fxneqB22ZQ6Hfk58OapLuPWXB+mISEzjpMb2u2yYVooelT2aoVHkCwN/w+jFDA1yEDssqkvvXFtW41iLpNAVKm6iAWHrNj+pCt3eT2DJ7HjN6Nx1rVSpKN/8K0qMzfiZ6ywDtrOP3E/1krmW4lm0RjxvRv4vQcH18M9aOdBPshmHK9qEKf9W/jbtxqs0qtBP0LcKXrgqcoy7ns2RBx57eAq51ZNopf7xCIUGh8hdu05AYuxmvGKwmGXzrhyHwEVbp30WPAy5wy6H2KJI/ypiof4ZdKHcCucRC7+X3WmYXnLZNtCddIfnjXlP/jb1jGd92ft0pf1aJbCjN7c1m1T/Hr4B3aFbIYMSMLGELK+wRrFh5TY+ma+316xivMkS5QhKbO/6i8nfC9uymrrxz9yZNLNZOga6jcqHPTYhHEHtZlc+hBC3VFwp8+KAa5UY2cn9ldWismaCvrf7he7T5r8xeiMlqB+VIHAXa87+vMHKtCxUot7uZwYr6P2w14A1Dmai0ICUbRpii0y8dux07kQ323f63KmJhnYyNPZrIpTiyEYmpcuRPnFjN7rbTDuNogO7jthKsh/Tyu75Pr4WZT+2gNIddwM1lWn12pRHUvC2U96oqUc/JYcjyN0+4eQXycRzVkttGKkcKzTQtbY3K5kCq3rtX+Pmk3ls9+4KuBwKFgo=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cameleon_web_sysctl.org
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
